LIB =	tinyxml

SRCS =				\
	tinystr			\
	tinyxml			\
	tinyxmlerror		\
	tinyxmlparser		

ifndef KBE_ROOT
export KBE_ROOT := $(subst /src/lib/dependencies/$(LIB),,$(CURDIR))
endif

include $(KBE_ROOT)/src/build/common.mak